/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
   @Test public  void x(){
       int[][] weeklyMonthTemperatures = {
               {66, 64, 58, 65, 71, 57, 60},
               {57, 65, 65, 70, 72, 65, 51},
               {55, 54, 60, 53, 59, 57, 61},
               {65, 56, 55, 52, 55, 62, 57}
       };
       String result = "Never saw temperature: " +73;
       assertEquals(result,Library.App.weeklyMonthTemperaturesFuncation(weeklyMonthTemperatures));

   }
}
