/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(),
                "app should have a greeting");
    }
    @Test public void weeklyMonthTemperaturesFuncationtest(){
        //High: 72 max
        //Low: 51 min
        //Never saw temperature: 63
        //Never saw temperature: 67
        //Never saw temperature: 68
        //Never saw temperature: 69
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int value=63;
String result="Never saw temperature: "+63;
// i try yo built but i have issue so i comment this line
   //assertEquals("this method supposed to use unique values not exsits in originalarray",result,App.weeklyMonthTemperaturesFuncation(weeklyMonthTemperatures));
    }
}
