/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.nio.file.Path;
import java.nio.file.Paths;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       // System.out.println(new App().getGreeting());
       // Path newpath= Paths.get("gates.js");try {
        //}
    }

}
