/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.ArrayList;
import java.util.List;
import java.util.*;

public class App {


    public static void main(String[] args) {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
    }

    public static int[] roll(int number) {
        int[] newArr = new int[number];
        int minimum = 1;
        int maximum = 6;

        for (int i = 0; i < number; i++) {
            int randomNum = minimum + (int) (Math.random() * maximum);
            newArr[i] = randomNum;
        }
        return newArr;
    }

    public static Boolean containsDuplicates(int[] containArray) {
        int[] NewContainArray = new int[containArray.length + 1];
        //List<Boolean> NewContainArrays=new ArrayList<Boolean>();
        for (int i : containArray) {
            for (int j : NewContainArray) {
                if (containArray[i] == containArray[j]) {
                    return true;
                }

            }
        }return false;

    }
    public static int CalculatingAverages(int[] CalculatingArray) {
  int total=0;
        for (int i : CalculatingArray){
            total+=i;

        }
return total/(CalculatingArray.length+1);
    }
    //public static int[] weeklyMonthTemperatures(int[][] CalculatingArrayOfArrays) {
        //int total=0;
//int []arr=
        //for (int i : CalculatingArrayOfArrays) {
           // for (int j : weeklyMonthTemperatures){
       // total+=j;
        //return total/(CalculatingArray.length+1);
           // }
        //}

    //}

    //}
}
