/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;

import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    public void  testLinterFunction(){
      Path newpathtest = Paths.get("app/src/main/resources/gates.js");
       // Path newpathtest = Paths.get("testGates.js");
        String result ="line"+" "+(3)+" you are missing semicolon";
        assertEquals(result,App.ReadFileScanerLinter(newpathtest));
    }

}
